# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute doubly centered matrix
#'
#' This function returns the doubly centered version of a matrix
#' @param x A matrix which to doubly center
#' @return Doubly centered version of a matrix
#' @export
dcenter <- function(x) {
    .Call(`_balanceAssessment_dcenter`, x)
}

#' Compute doubly centered matrix
#'
#' This function returns the doubly centered version of a matrix
#' @param x A matrix which to doubly center
#' @param w A matrix containing weights
#' @return Doubly centered version of a matrix
#' @export
weighted_dcenter <- function(x, w) {
    .Call(`_balanceAssessment_weighted_dcenter`, x, w)
}

#' Weighted mean
#'
#' This function returns the weighted mean of a vector
#' @param x A numeric vector for which to compute the weighted mean
#' @param w A numeric vector of the same length as x
#' @return Returns the weighted mean
#' @export
weighted_mean <- function(x, w) {
    .Call(`_balanceAssessment_weighted_mean`, x, w)
}

#' Weighted variance
#'
#' This function returns the weighted variance of a vector
#' @param x A numeric vector for which to compute the weighted variance
#' @param w A numeric vector of the same length as x, with frequency weights (i.e. sum of weights is equal to number of occurrences)
#' @return Returns the weighted variance
#' @export
weighted_var <- function(x, w) {
    .Call(`_balanceAssessment_weighted_var`, x, w)
}

#' Weighted sd
#'
#' This function returns the weighted sd of a vector
#' @param x A numeric vector for which to compute the weighted sd
#' @param w A numeric vector of the same length as x, with frequency weights (i.e. the sum of weights is equal to the number of occurrences)
#' @return Returns the weighted sd
#' @export
weighted_sd <- function(x, w) {
    .Call(`_balanceAssessment_weighted_sd`, x, w)
}

